import type { ShopifyProduct } from './types';

export const products: ShopifyProduct[] = [
  {
    id: 1,
    title: 'Classic Leather Wallet',
    description:
      'A timeless bifold wallet crafted from genuine full-grain leather. Features multiple card slots, a clear ID window, and a spacious bill compartment. Perfect for everyday use.',
    vendor: 'Heritage Leather',
    product_type: 'Accessories',
    price: 79.99,
    inventory: 120,
    imageUrl: 'https://picsum.photos/seed/101/600/400',
    imageHint: 'leather wallet',
    unitsSold: 1502,
    totalRevenue: 120144.98,
    averageRating: 4.8,
    numberOfReviews: 312,
  },
  {
    id: 2,
    title: 'Ergonomic Office Chair',
    description:
      'Experience ultimate comfort and support with our ergonomic office chair. Features adjustable lumbar support, 4D armrests, a breathable mesh back, and a smooth recline function.',
    vendor: 'ComfortZone',
    product_type: 'Furniture',
    price: 349.5,
    inventory: 45,
    imageUrl: 'https://picsum.photos/seed/102/600/400',
    imageHint: 'office chair',
    unitsSold: 421,
    totalRevenue: 147139.5,
    averageRating: 4.6,
    numberOfReviews: 129,
  },
  {
    id: 3,
    title: 'Wireless Noise-Cancelling Headphones',
    description:
      'Immerse yourself in pure sound. These headphones offer industry-leading noise cancellation, high-resolution audio, and up to 30 hours of battery life on a single charge.',
    vendor: 'AudioPhonic',
    product_type: 'Electronics',
    price: 299.0,
    inventory: 88,
    imageUrl: 'https://picsum.photos/seed/103/600/400',
    imageHint: 'wireless headphones',
    unitsSold: 2340,
    totalRevenue: 699660.0,
    averageRating: 4.9,
    numberOfReviews: 1805,
  },
  {
    id: 4,
    title: 'Smart Coffee Maker',
    description:
      'Brew the perfect cup every time with this Wi-Fi enabled smart coffee maker. Schedule brewing, adjust strength, and more, all from your smartphone. Compatible with Alexa and Google Assistant.',
    vendor: 'BrewMaster',
    product_type: 'Home Appliances',
    price: 129.95,
    inventory: 65,
    imageUrl: 'https://picsum.photos/seed/104/600/400',
    imageHint: 'coffee maker',
    unitsSold: 855,
    totalRevenue: 111107.25,
    averageRating: 4.5,
    numberOfReviews: 240,
  },
  {
    id: 5,
    title: 'Organic Cotton T-Shirt',
    description:
      'A wardrobe essential, this t-shirt is made from 100% GOTS-certified organic cotton for a soft, comfortable feel. Ethically made and built to last.',
    vendor: 'EcoThreads',
    product_type: 'Apparel',
    price: 24.99,
    inventory: 350,
    imageUrl: 'https://picsum.photos/seed/105/600/400',
    imageHint: 'cotton t-shirt',
    unitsSold: 5430,
    totalRevenue: 135695.7,
    averageRating: 4.7,
    numberOfReviews: 890,
  },
  {
    id: 6,
    title: 'Portable Bluetooth Speaker',
    description:
      'Take your music anywhere. This rugged, waterproof speaker delivers powerful sound and deep bass. With a 24-hour playtime, the party never has to stop.',
    vendor: 'SoundWave',
    product_type: 'Electronics',
    price: 99.99,
    inventory: 150,
    imageUrl: 'https://picsum.photos/seed/106/600/400',
    imageHint: 'bluetooth speaker',
    unitsSold: 1120,
    totalRevenue: 111988.8,
    averageRating: 4.6,
    numberOfReviews: 455,
  },
  {
    id: 7,
    title: 'Stainless Steel Water Bottle',
    description:
      'Stay hydrated on the go. This double-wall insulated bottle keeps drinks cold for 24 hours or hot for 12. Made from durable, food-grade stainless steel.',
    vendor: 'HydraPeak',
    product_type: 'Kitchenware',
    price: 34.95,
    inventory: 210,
    imageUrl: 'https://picsum.photos/seed/107/600/400',
    imageHint: 'water bottle',
    unitsSold: 3105,
    totalRevenue: 108519.75,
    averageRating: 4.9,
    numberOfReviews: 1023,
  },
  {
    id: 8,
    title: 'Yoga Mat Pro',
    description:
      'Find your flow on our premium non-slip yoga mat. Made from eco-friendly, natural tree rubber, it provides excellent cushioning and grip for any practice.',
    vendor: 'ZenFlow',
    product_type: 'Sports & Outdoors',
    price: 89.0,
    inventory: 95,
    imageUrl: 'https://picsum.photos/seed/108/600/400',
    imageHint: 'yoga mat',
    unitsSold: 980,
    totalRevenue: 87220.0,
    averageRating: 4.8,
    numberOfReviews: 350,
  },
];
